#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Repo Dispatcher

on: 
  # push: 
  #   branches:
  #     - master
  #schedule:
  #  - cron: 30 18 * * *
  workflow_dispatch:
    inputs:
      param:
        description: 'parameter'
        required: false
        default: ''

env:
  TOKEN_KIDDIN9: ${{ secrets.TOKEN_KIDDIN9 }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: cancel running workflows
      uses: styfle/cancel-workflow-action@main
      if: contains(github.event.inputs.param, 'cw')
      with:
        workflow_id: all
        access_token: ${{ secrets.TOKEN_KIDDIN9 }}

    - name: Load Settings.ini
      run: |
        source "${GITHUB_WORKSPACE}/devices/common/settings.ini"
        if [ -f "devices/${{matrix.target}}/settings.ini" ]; then
          source "${GITHUB_WORKSPACE}/devices/${{matrix.target}}/settings.ini"
        fi
        echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV
        echo "REPO_BRANCH=${REPO_BRANCH}" >> $GITHUB_ENV

    - name: Trigger Packages Update
      run: |
        gitdate=$(curl -H "Authorization: token ${{ secrets.TOKEN_KIDDIN9 }}" -s "https://api.github.com/repos/kiddin9/kwrt-packages/actions/runs" | jq -r '.workflow_runs[0].created_at')
        gitdate=$(date -d "$gitdate" +%s)
        now=$(date -d "$(date)" +%s)
        if [[ $(expr $gitdate + 120) < $now ]]; then
        curl -X POST https://api.github.com/repos/kiddin9/kwrt-packages/dispatches \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Authorization: token ${{ secrets.TOKEN_KIDDIN9 }}" \
        --data '{"event_type": "update"}'
        fi

    - name: Trigger Compile
      run: |
        sudo timedatectl set-timezone "$TZ"
        allowed_targets=("x86_64" "x86_generic" "rockchip_armv8" "bcm27xx_bcm2712" "bcm27xx_bcm2711" "bcm27xx_bcm2710" "bcm27xx_bcm2709" "bcm27xx_bcm2708" "armsr_armv8" "mediatek_mt7622" "mediatek_filogic" "qualcommax_ipq50xx" "ramips_mt7621" "ramips_mt7620" "ramips_mt76x8" "qualcommax_ipq807x" "ipq40xx_generic" "ipq806x_generic" "amlogic_meson8b" "qualcommax_ipq60xx" "mvebu_cortexa9" "bcm53xx" "sunxi_cortexa53" "sunxi_cortexa7" "ath79_nand")
        target=$(echo "${GITHUB_EVENT_INPUT_PARAM}" | tr '[:upper:]' '[:lower:]')
        if [[ " ${allowed_targets[@]} " =~ " ${target} " ]]; then
          curl \
          -X POST https://api.github.com/repos/${GITHUB_REPOSITORY}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${TOKEN_KIDDIN9}" \
          -d '{"event_type": "'"${target}"'", "client_payload": {"target": "'"${target}"'"}}'
        fi
